
server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reward?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ljb112233
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    com.chuwa.reward: DEBUG